# Makefile genérico para un solo ejercicio C++

CXX := g++
CXXFLAGS := -std=c++98 -O2 -Wall -Wextra -Wpedantic
INCLUDES := -Iinclude
SRC_DIR := src

EX ?= 1-2026_rutaDefensa
SRC := $(SRC_DIR)/$(EX).cpp
OUT := arboles

.PHONY: all build run clean

all: build

build:
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(SRC) -o $(OUT)

run: build
	./$(OUT)

clean:
	rm -rf $(BIN_DIR)
